### ISSUE TITLE
Workstream definition: Runtime initialization, finalization, entrypoint marking and runtime parameter input

### ISSUE THREAD

**Issue by amccaskey** [qir-alliance/.github#16]
This issue is created to capture any discussions or feedback also from the broader community regarding the creation of a workstream to investigate runtime library initialization, finalization, and command line input for custom entrypoints. 

QIR implementation libraries provided at link time may need to rely on library start-up and finalization routines in order to properly configure and tear-down an underlying simulation and / or remote job submission infrastructure. Runtime initialization also raises the question of how QIR lowering strategies should specify entry point functions and corresponding input data provided at runtime.

The [workstream definition document](https://github.com/amccaskey/.github/blob/main/workstreams/Runtime_Init_Finalize_EntryPoint_Workstream.md) captures the goals, requirements, expected outcomes, as well as what is in and out of scope for the workstream. Please comment on this issue to share thoughts about the workstream itself (i.e. about the content of that document).

**Comment by bettinaheim** [comment]
Discussion points that came up during the SC meeting:
- The exact scope of the workstream needs to be further clarified. 
   Is the workstream focused only on entry point handling or should methods for runtime initialization and finalization also available independently (e.g. for interop scenarios)?
- What are the restrictions/requirements for entry points and their arguments?
   How exactly should program arguments be instantiated (where does the conversion from string to IR value happen)?
- Can we ensure that the entry point handling is consistent for both local execution/simulation and for cloud-based execution on a quantum backend?
- Considerations around the linking stage may be relevant both for this workstream and for the Base Profile workstream
